# -*- coding: utf-8 -*-
"""clean_Script.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nz5OzWg_ZKQHNpA7gwwBW_cX1SyR9PJE
"""

import csv

clean_prompts = [
    {"id": 1, "question": "Who wrote 'The Great Gatsby'?", "gold_answer": "F. Scott Fitzgerald"},
    {"id": 2, "question": "Which play features Lady Macbeth?", "gold_answer": "Macbeth"},
    {"id": 3, "question": "What is the term for a 14-line poem?", "gold_answer": "Sonnet"},
    {"id": 4, "question": "Who created Sherlock Holmes?", "gold_answer": "Arthur Conan Doyle"},
    {"id": 5, "question": "Which novel begins with 'Call me Ishmael'?", "gold_answer": "Moby-Dick"},
    {"id": 6, "question": "Who wrote 'Pride and Prejudice'?", "gold_answer": "Jane Austen"},
    {"id": 7, "question": "What is the pen name of Samuel Clemens?", "gold_answer": "Mark Twain"},
    {"id": 8, "question": "Which epic poem features Achilles?", "gold_answer": "The Iliad"},
    {"id": 9, "question": "Who is the author of '1984'?", "gold_answer": "George Orwell"},
    {"id": 10, "question": "What is the genre of 'Dracula'?", "gold_answer": "Gothic"},
    {"id": 11, "question": "Who wrote 'The Waste Land'?", "gold_answer": "T. S. Eliot"},
    {"id": 12, "question": "Which Shakespeare play has a jealous Moor?", "gold_answer": "Othello"},
    {"id": 13, "question": "Who wrote 'The Catcher in the Rye'?", "gold_answer": "J. D. Salinger"},
    {"id": 14, "question": "What is the term for a play's list of characters?", "gold_answer": "Dramatis personae"},
    {"id": 15, "question": "Who wrote 'Crime and Punishment'?", "gold_answer": "Dostoevsky"},
    {"id": 16, "question": "Which novel features Atticus Finch?", "gold_answer": "To Kill a Mockingbird"},
    {"id": 17, "question": "Who wrote 'The Divine Comedy'?", "gold_answer": "Dante"},
    {"id": 18, "question": "What is the term for a story within a story?", "gold_answer": "Frame narrative"},
    {"id": 19, "question": "Who wrote 'Brave New World'?", "gold_answer": "Aldous Huxley"},
    {"id": 20, "question": "Which author created Hercule Poirot?", "gold_answer": "Agatha Christie"},
    {"id": 21, "question": "What is the term for a Japanese poem of 17 syllables?", "gold_answer": "Haiku"},
    {"id": 22, "question": "Who wrote 'The Old Man and the Sea'?", "gold_answer": "Ernest Hemingway"},
    {"id": 23, "question": "Which novel features Big Brother?", "gold_answer": "1984"},
    {"id": 24, "question": "Who wrote 'The Picture of Dorian Gray'?", "gold_answer": "Oscar Wilde"},
    {"id": 25, "question": "What is the term for a recurring theme in literature?", "gold_answer": "Motif"},
    {"id": 26, "question": "Who directed 'Jurassic Park'?", "gold_answer": "Steven Spielberg"},
    {"id": 27, "question": "Which band released 'Abbey Road'?", "gold_answer": "The Beatles"},
    {"id": 28, "question": "Who played Iron Man in the MCU?", "gold_answer": "Robert Downey Jr."},
    {"id": 29, "question": "What is the name of Mario's brother?", "gold_answer": "Luigi"},
    {"id": 30, "question": "Which TV show features Walter White?", "gold_answer": "Breaking Bad"},
    {"id": 31, "question": "Who created Batman?", "gold_answer": "Bob Kane"},
    {"id": 32, "question": "Which film won Best Picture in 1994?", "gold_answer": "Forrest Gump"},
    {"id": 33, "question": "Who sang 'Thriller'?", "gold_answer": "Michael Jackson"},
    {"id": 34, "question": "What is the name of Link's sword?", "gold_answer": "Master Sword"},
    {"id": 35, "question": "Which comic features the Joker?", "gold_answer": "Batman"},
    {"id": 36, "question": "Who directed 'Inception'?", "gold_answer": "Christopher Nolan"},
    {"id": 37, "question": "Which game features Pikachu?", "gold_answer": "Pokémon"},
    {"id": 38, "question": "Who played Hermione Granger?", "gold_answer": "Emma Watson"},
    {"id": 39, "question": "Which band released 'Bohemian Rhapsody'?", "gold_answer": "Queen"},
    {"id": 40, "question": "What is the name of Sonic's sidekick?", "gold_answer": "Tails"},
    {"id": 41, "question": "Who created Spider-Man?", "gold_answer": "Stan Lee"},
    {"id": 42, "question": "Which film features the DeLorean?", "gold_answer": "Back to the Future"},
    {"id": 43, "question": "Who sang 'Like a Virgin'?", "gold_answer": "Madonna"},
    {"id": 44, "question": "Which TV show features Eleven?", "gold_answer": "Stranger Things"},
    {"id": 45, "question": "Who directed 'Pulp Fiction'?", "gold_answer": "Quentin Tarantino"},
    {"id": 46, "question": "Which game series features Master Chief?", "gold_answer": "Halo"},
    {"id": 47, "question": "Who played Jack Sparrow?", "gold_answer": "Johnny Depp"},
    {"id": 48, "question": "Which comic features Magneto?", "gold_answer": "X-Men"},
    {"id": 49, "question": "Who sang 'Purple Rain'?", "gold_answer": "Prince"},
    {"id": 50, "question": "Which film features the Millennium Falcon?", "gold_answer": "Star Wars"}
    ]

with open('clean_prompts.csv', 'w', newline='', encoding='utf-8') as csvfile:
    fieldnames = ['id', 'question', 'gold_answer']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(clean_prompts)

